version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro

  db:
    image: postgres
    container_name: csim-postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      # Volume de la base de données
      - ./csim-db-pg:/var/lib/pgsql-v1
    environment:
      - POSTGRES_DB=csim
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - PGDATA=/var/lib/pgsql-v1
    networks:
      - vpcbr

  web:
    container_name: csim-frontend
    ports:
      # local:container
      - "8080:8080"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/csim-frontend
    env_file:
      - csim-front.env
    volumes:
      # Volume stockant les fichiers web du projet
      - ./:/var/www/html/csim-frontend
    build:
      context: ./CSIM-Front/
      dockerfile: Dockerfile
    image: csim-frontend
    depends_on:
      - api
      - webserver
    links:
      # Lien vers le conteneur "api" (déclaré ci-après)
      - api:api
    networks:
      - vpcbr

  api:
    container_name: csim-backend
    ports:
      # local:container
      - "3031:3031"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/csim-backend
      - DATABASE_URL=postgres://username:pgpassword@db:5432/mydatabase
    env_file:
      - csim-back.env
    volumes:
      # Volume stockant les fichiers web du projet
      - ./:/var/www/html/csim-backend
    build:
      context: ./CSIM-Back/
      dockerfile: Dockerfile
    image: csim-backend
    depends_on:
      - db
    links:
      # Lien vers le conteneur "db" (déclaré ci-après)
      - db:db
    networks:
      - vpcbr

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
